#![allow(dead_code, unused_imports)]
mod array_and_string;
mod bit_manipulation;
mod combinatorics;
mod dynamic_programming;
mod example_problem;
mod general_programming;
mod greedy_algorithms;
mod hashing_and_hash_tables;
mod linked_lists;
mod queues_and_stacks;
mod searching_and_sorting;
mod trees_and_graphs;
